napendice/applications/miscelanea/urls.py
# django
from django.conf.urls import include, url

# local
from . import views

app_name="miscelanea_app"

urlpatterns = [
    url(
        r'^lista-categorias/$',
        views.ListaCategoriasView.as_view(),
        name='category-list'
    ),
]

napendice/napendice/urls.py
#
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #urls para miscelanea
    url(r'^', include('applications.miscelanea.urls')),
    # urls para la aplicacion home
    url(r'^', include('applications.home.urls')),
    # urls para la aplicacion articulo
    url(r'^', include('applications.articulo.urls')),
    #
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

napendice/applications/miscelanea/models.py
# future
from __future__ import unicode_literals
import os

# third-party
from model_utils.models import TimeStampedModel

# django
from django.db import models
from django.contrib.auth.models import User

#manager
from .managers import CategoryManager

# Create your models here.

class Category(TimeStampedModel):
    '''
    modelo para almacenar categorias
    '''
    name = models.CharField('nombre', max_length=150)

    objects = CategoryManager()

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name


class Tag(TimeStampedModel):
    '''modelo djanog para etiquetas'''

    name = models.CharField('nombre', max_length=150)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Medios(TimeStampedModel):
    name = models.CharField(
        blank=True,
        max_length=100
    )
    files = models.FileField(
        upload_to='files',
        blank=True,
        null=True,
    )
    files_url = models.URLField(
        blank=True,
    )

    class Meta:
        verbose_name = 'Medio'
        verbose_name_plural = 'Medios'

    def delete(self,*args,**kwargs):
        if os.path.isfile(self.files.path):
            os.remove(self.files.path)

        super(Medios, self).delete(*args,**kwargs)

    def __str__(self):
        return str(self.files)

napendice/applications/miscelanea/forms.py
from django import forms

#import models
#from .models import Medios


# class MediosForm(forms.ModelForm):
#     """"Tabla para Alamacenar Medios"""
#
#     class Meta:
#         model = Medios
#         fields = (
#             'name',
#             'files',
#         )
#         widgets = {
#             'name': forms.TextInput(
#                 attrs={
#                     'placeholder': 'nombre para el archivo o imagen'
#                 }
#             ),
#         }

napendice/applications/miscelanea/views.py
# -*- coding: utf-8 -*-
# django
from django.urls import reverse_lazy, reverse
from django.conf import settings
#
from django.views.generic import TemplateView, ListView, DeleteView
from django.views.generic.edit import CreateView

#import models
#from .models import Medios

#import forms
#from .forms import MediosForm


# class MediosCreateView(CreateView):
#     """Metodo para Guardar Medios"""
#
#     form_class = MediosForm
#     success_url = reverse_lazy('miscelanea_app:medios-list')
#     template_name = 'miscelanea/medios/add.html'
#
#     def form_valid(self, form):
#         medios = form.save(commit=False)
#         #recuperamos la url
#         medios.files_url = "http://apendice.pe"+medios.files.url
#         medios.save()
#
#         return super(MediosCreateView, self).form_valid(form)


# class MediosListView(ListView):
#     """Vista que lista los archivos Media"""
#
#     context_object_name = 'list_medios'
#     #model = Medios
#     template_name = 'miscelanea/medios/list.html'


# class MediosDeleteView(DeleteView):
#     model = Medios
#     success_url = reverse_lazy('miscelanea_app:medios-list')
#     template_name = 'miscelanea/medios/delete.html'



class ListaCategoriasView(TemplateView):
    template_name = 'miscelanea/list.html'

napendice/templates/miscelanea/medios/add.html
{% extends "miscelanea/base_miscelanea.html" %}

{% load staticfiles %}

{% block title %}
 Agregar Medios
{% endblock %}

{% block content %}
    {% include "include/menu.html" %}

    <div class="large-12 columns">
      <div class="row">
        <div class="callout">
          <p>
            Añadir Nueva Nota
          </p>
        </div>
      </div>

      <div class="row">
        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
          <div class="callout">
            <label>Descripcion de Imagen
              {{form.name}}
            </label>
            <label for="id_files" class="button">Archivo o Imagen</label>
            {{form.files}}
          </div>
          <button type="submit" class="success button">Guardar</button>
        </form>
      </div>
    </div>

{% endblock %}

napendice/templates/miscelanea/medios/delete.html
{% extends "miscelanea/base_miscelanea.html" %}

{% load staticfiles %}

{% block title %}
 Eliminar Archivo
{% endblock %}

{% block content %}

    {% include "include/menu.html" %}

    <h1 class="page-title">Eliminar<span class="fw-semi-bold"> Archivo</span></h1>
    <div class="col-md-6">
      <section class="callout">
        <div class="callout">
            <form role="form" action="{% url 'miscelanea_app:medios-delete' medios.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="row">
                    <div class="row center">
                        <div class="large-4 columns">
                            <div>
                                ¿Esta seguro de Eliminar: <span>{{medios.name}}</span>?.
                            </div>
                            <button type="submit" class="alert button">Eliminar</button>
                            <a href="{% url 'miscelanea_app:medios-list' %}" class="btn btn-inverse">Cancel</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
      </section>
    </div>

{% endblock %}

napendice/templates/miscelanea/medios/list.html
{% extends "miscelanea/base_miscelanea.html" %}

{% load staticfiles %}

{% block title %}
 Lista de Medios
{% endblock %}

{% block content %}
    {% include "include/menu.html" %}

    <div class="large-12 columns">
      <div class="row">
        <div class="callout">
          <p>
            Lista de Fotos y Archivos Guardados <a href="{% url 'miscelanea_app:medios-add' %}" class="button secondary small" type="button">
              <span aria-hidden="true">Nuevo</span>
            </a>
          </p>
        </div>
      </div>

      <div class="row">
        {% for l in list_medios  %}
        <div class="medium-4 columns">
          <div class="card" style="height: 300px;">
            <div class="card-divider">
              <h5>{{l.name}}</h5>
              <h7>URL:<a href="{{l.files.url}}">{{l.files_url}}</a></h7>
              <a href="{% url 'miscelanea_app:medios-delete' l.pk %}" class="button alert tiny" type="button">
                <span aria-hidden="true">Eliminar</span>
              </a>
            </div>
            {% if l.files.url != None %}
              <img src="{{l.files.url}}">
            {% else %}
              <img src="{% static 'img/file.png' %}">
              {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

{% endblock %}