napendice/applications/articulo/urls.py
# django
from django.conf.urls import include, url

# local
from . import views

app_name="articulo_app"

urlpatterns = [

    # urls para la aplicacion articulo
    url(
        r'^ultimas-noticias-peru/$',
        views.ArticleListView.as_view(),
        name='article-list'
    ),
    url(
        r'^(?P<category>[-\w]+)/(?P<pk>\d+)/$',
        views.ArticleCategoryView.as_view(),
        name='article-category'
    ),
    url(
        r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.ArticleDetailView.as_view(),
        name='article-detail'
    ),

]

napendice/applications/home/urls.py
# django
from django.conf.urls import include, url

# local
from . import views

app_name="home_app"

urlpatterns = [
    # urls para la aplicacion home
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^buscar-noticias/$',
        views.ArticleListView.as_view(),
        name='buscar'
    ),
]

napendice/napendice/urls.py
#
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #urls para miscelanea
    url(r'^', include('applications.miscelanea.urls')),
    # urls para la aplicacion home
    url(r'^', include('applications.home.urls')),
    # urls para la aplicacion articulo
    url(r'^', include('applications.articulo.urls')),
    #
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

napendice/applications/home/models.py
# future
from __future__ import unicode_literals

# third-party
from model_utils.models import TimeStampedModel

# django
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Home(TimeStampedModel):

    title = models.CharField('titulo', max_length=200)
    image = models.ImageField(
        'imagen de banner',
        upload_to='home',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Banner Pricipal'
        verbose_name_plural = 'Banners'
        ordering = ['-created']

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class Contact(TimeStampedModel):
    """Django data model Contact"""

    name = models.CharField('nombre', blank=True, max_length=100)
    email = models.EmailField('email')
    telephone = models.CharField('telefono', blank=True, max_length=12)
    subject = models.CharField('asunto', max_length=50)
    send = models.CharField('consulta', max_length=150)

    class Meta:
        verbose_name = 'Tipo de Contacto'
        verbose_name_plural = 'Tipos de Contactos'

    def __str__(self):
        return self.name

napendice/applications/home/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'telephone',
            'subject',
            'send',
        ]
        labels = {
            'name': 'nombre',
            'email': 'email',
            'telephone': 'telefono',
            'subject': 'asunto',
            'send': 'consulta',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'telephone':forms.TextInput(attrs={'class':'form-control'}),
            'subject':forms.TextInput(attrs={'class':'form-control'}),
            'send':forms.Textarea(attrs={'class':'form-control'}),
        }


class SearchForm(forms.Form):
    '''
    formulario para buscar notas
    '''
    kword = forms.CharField(
        max_length='300',
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Buscar',
                'class': 'principal-header__search__input'
            }
        )
    )

napendice/applications/home/views.py
# -*- coding: utf-8 -*-
# django
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.views.generic import ListView

# local
from .models import Contact, Home
from .forms import ContactForm, SearchForm
from applications.articulo.models import Article

#
from applications.mixins import UpdateArticlesMixin
# Create your views here.


class ContactCreateView(UpdateArticlesMixin, CreateView):
    '''
    formulario de contactenos
    '''
    model = Contact
    form_class = ContactForm
    success_url = '/'
    template_name = 'contact/index.html'

    def get_context_data(self, **kwargs):
        context = super(ContactCreateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            contact = form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class IndexView(UpdateArticlesMixin, TemplateView):
    '''
    Pagina principal de apendice donde se van a mostrar las noticias mas
    importantes del dia
    '''

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['portada'] = Article.objects.portada()
        context['destacados'] = Article.objects.outstanding()
        context['standar'] = Article.objects.standar()
        #
        context['form'] = SearchForm
        return context

    template_name = 'home/index.html'


class ArticleListView(UpdateArticlesMixin, ListView):
    context_object_name = 'articles'
    model = Article
    template_name = 'home/search.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['form'] = SearchForm
        context['standar'] = Article.objects.standar()
        return context

    def get_queryset(self):
        #recuperamos el valor por GET
        q = self.request.GET.get("kword", '')
        queryset = Article.objects.search_article(q)
        return queryset

napendice/templates/home/base_home.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock css %}

{% block js %}
  <!-- Javascrip para foundtion -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/fontawesome-all.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/scrips.js' %}"></script>
  <!-- Javascrip para foundation -->

  <!-- analytics google-->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88164012-1', 'auto');
  ga('send', 'pageview');

</script>
{% endblock js %}

napendice/templates/home/index.1.html
{% extends "home/base_home.html" %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Noticias del Perú y el mundo |
  {{ portada.title }} |
  {% for destacado in destacados %}
    {{ destacado.title }} |
  {% endfor %}
    apendice | apendicepe
{% endblock %}

{% block description %}
  Noticias del Perú y el mundo, ultimas noticas de politica, investigacion, actualidad, gobierno, peru, en apendice.pe.
{% endblock %}

{% block content %}
  {% include "include/header.html" %}
  <main class="main">
    <div class="news-columns">
      <div class="news-column">
        <article class="news news--home">
          <div class="news__image">
            <img src="{{ portada.image.url }}" alt="{{ portada.title }}" />
            {% if portada.category|slugify == 'lima' %}
            <span class="news__category--investigation">{{ portada.category }}</span>
            {% elif  portada.category|slugify == 'politica' %}
            <span class="news__category--politics">{{ portada.category }}</span>
            {% elif  portada.category|slugify == 'miscelanea' %}
            <span class="news__category--miscelanea">{{ portada.category }}</span>
            {% else %}
            <span class="news__category--topicality" style="background:#039be5;">{{ portada.category }}</span>
            {% endif %}
          </div>


          <div class="news__body">
            {% if portada.date != '' %}
              <div class="news__date">Hace {{ portada.date|timesince }}</div>
            {% else %}
              <div class="news__date">Hace {{ portada.created|timesince }}</div>
            {% endif %}

            <h1 class="news__title--home">
              <a href="{% url 'articulo_app:article-detail' portada.category|slugify portada.slug %}">
                {{ portada.title }}
              </a>
            </h1>
            <p class="news__description">{{ portada.description }}</p>
            <a href="{% url 'articulo_app:article-detail' portada.category|slugify portada.slug %}" class="news__link">Ver más...</a>
          </div>
        </article>

      </div>

      <div class="news-column">

        {% for destacado in destacados %}
          <article class="news news--outstanding">
            <div class="news__image">
              <img src="{{ destacado.image.url }}" alt="{{ destacado.title }}" />
              {% if destacado.category|slugify == 'investigacion' %}
              <div class="news__category--investigation">{{ destacado.category }}</div>
              {% elif  destacado.category|slugify == 'politica' %}
              <div class="news__category--politics">{{ destacado.category }}</div>
              {% elif  destacado.category|slugify == 'miscelanea' %}
              <div class="news__category--miscelanea">{{ destacado.category }}</div>
              {% else %}
              <div class="news__category--topicality">{{ destacado.category }}</div>
              {% endif %}
            </div>


            <div class="news__body">
              {% if destacado.date != '' %}
                <div class="news__date">Hace {{ destacado.date|timesince }}</div>
              {% else %}
                <div class="news__date">Hace {{ destacado.created|timesince }}</div>
              {% endif %}

              <h2 class="news__title--outstanding">
                <a href="{% url 'articulo_app:article-detail' destacado.category|slugify destacado.slug %}">
                  {{ destacado.title }}
                </a>
              </h2>
              <p class="news__description--outstanding">{{ destacado.description|truncatechars_html:130  }}</p>
              <a href="{% url 'articulo_app:article-detail' destacado.category|slugify destacado.slug %}" class="news__link">Ver más...</a>
            </div>
          </article>
        {% endfor %}

      </div>
    </div> <!-- fin de noticias principales -->

    <div class="ed-container">
      <div class="ed-item s-100">
        <div class="divider--top"></div>
      </div>
      <div class="ed-item">
        <h3 class="title-more-news">
          Más noticias
        </h3>
      </div>
    </div>

    <div class="ed-container">

      {% for news in standar %}

        <article class="ed-item s-100 m-1-3 l-25 news news--standar">
          <div class="news__image">
            <img src="{{ news.image.url }}" alt="{{ news.title }}" />
            {% if news.category|slugify == 'investigacion' %}
            <div class="news__category--investigation">{{ news.category }}</div>
            {% elif  news.category|slugify == 'politica' %}
            <div class="news__category--politics">{{ news.category }}</div>
            {% elif  news.category|slugify == 'miscelanea' %}
            <div class="news__category--miscelanea">{{ news.category }}</div>
            {% else %}
            <div class="news__category--topicality">{{ news.category }}</div>
            {% endif %}
          </div>

          <div class="news__body">
            {% if news.date != '' %}
              <div class="news__date">Hace {{ news.date|timesince }}</div>
            {% else %}
              <div class="news__date">Hace {{ news.created|timesince }}</div>
            {% endif %}

            <h2 class="news__title--outstanding">
              <a href="{% url 'articulo_app:article-detail' news.category|slugify news.slug %}">
                {{ news.title }}
              </a>
            </h2>
            <p class="news__description--outstanding">{{ news.description|truncatechars_html:90 }}</p>
            <a href="{% url 'articulo_app:article-detail' news.category|slugify news.slug %}" class="news__link">Ver más...</a>
          </div>
        </article>

      {% endfor %}

    </div> <!-- fin de noticas standar -->

  </main>
  {% include "include/footer.html" %}

{% endblock %}

napendice/templates/home/index.html
{% extends "home/base_home.html" %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Noticias del Perú y el mundo |
  {{ portada.title }} |
  {% for destacado in destacados %}
    {{ destacado.title }} |
  {% endfor %}
    apendice | apendicepe
{% endblock %}

{% block description %}
  Noticias del Perú y el mundo, ultimas noticas de politica, investigacion, actualidad, gobierno, peru, en apendice.pe.
{% endblock %}

{% block content %}
  {% include "include/header.html" %}
  <main class="main">
    <div class="news-columns">
      <div class="news-column">
        <article class="news news--home">
          <div class="news__image">
            <img src="{{ portada.image.url }}" alt="{{ portada.title }}" />
            {% if portada.category|slugify == 'lima' %}
            <span class="news__category--investigation">{{ portada.category }}</span>
            {% elif  portada.category|slugify == 'politica' %}
            <span class="news__category--politics">{{ portada.category }}</span>
            {% elif  portada.category|slugify == 'miscelanea' %}
            <span class="news__category--miscelanea">{{ portada.category }}</span>
            {% else %}
            <span class="news__category--topicality" style="background:#039be5;">{{ portada.category }}</span>
            {% endif %}
          </div>


          <div class="news__body">
            {% if portada.date != '' %}
              <div class="news__date">Hace {{ portada.date|timesince }}</div>
            {% else %}
              <div class="news__date">Hace {{ portada.created|timesince }}</div>
            {% endif %}

            <h1 class="news__title--home">
              <a href="{% url 'articulo_app:article-detail' portada.category|slugify portada.slug %}">
                {{ portada.title }}
              </a>
            </h1>
            <p class="news__description">{{ portada.description }}</p>
            <a href="{% url 'articulo_app:article-detail' portada.category|slugify portada.slug %}" class="news__link">Ver más...</a>
          </div>
        </article>

      </div>

      <div class="news-column">

        {% for destacado in destacados %}
          <article class="news news--outstanding">
            <div class="news__image">
              <img src="{{ destacado.image.url }}" alt="{{ destacado.title }}" />
              {% if destacado.category|slugify == 'investigacion' %}
              <div class="news__category--investigation">{{ destacado.category }}</div>
              {% elif  destacado.category|slugify == 'politica' %}
              <div class="news__category--politics">{{ destacado.category }}</div>
              {% elif  destacado.category|slugify == 'miscelanea' %}
              <div class="news__category--miscelanea">{{ destacado.category }}</div>
              {% else %}
              <div class="news__category--topicality">{{ destacado.category }}</div>
              {% endif %}
            </div>


            <div class="news__body">
              {% if destacado.date != '' %}
                <div class="news__date">Hace {{ destacado.date|timesince }}</div>
              {% else %}
                <div class="news__date">Hace {{ destacado.created|timesince }}</div>
              {% endif %}

              <h2 class="news__title--outstanding">
                <a href="{% url 'articulo_app:article-detail' destacado.category|slugify destacado.slug %}">
                  {{ destacado.title }}
                </a>
              </h2>
              <p class="news__description--outstanding">{{ destacado.description|truncatechars_html:130  }}</p>
              <a href="{% url 'articulo_app:article-detail' destacado.category|slugify destacado.slug %}" class="news__link">Ver más...</a>
            </div>
          </article>
        {% endfor %}

      </div>
    </div> <!-- fin de noticias principales -->

    <div class="ed-container">
      <div class="ed-item s-100">
        <div class="divider--top"></div>
      </div>
      <div class="ed-item">
        <h3 class="title-more-news">
          Más noticias
        </h3>
      </div>
    </div>

    <div class="ed-container">

      {% for news in standar %}

        <article class="ed-item s-100 m-1-3 l-25 news news--standar">
          <div class="news__image">
            <img src="{{ news.image.url }}" alt="{{ news.title }}" />
            {% if news.category|slugify == 'investigacion' %}
            <div class="news__category--investigation">{{ news.category }}</div>
            {% elif  news.category|slugify == 'politica' %}
            <div class="news__category--politics">{{ news.category }}</div>
            {% elif  news.category|slugify == 'miscelanea' %}
            <div class="news__category--miscelanea">{{ news.category }}</div>
            {% else %}
            <div class="news__category--topicality">{{ news.category }}</div>
            {% endif %}
          </div>

          <div class="news__body">
            {% if news.date != '' %}
              <div class="news__date">Hace {{ news.date|timesince }}</div>
            {% else %}
              <div class="news__date">Hace {{ news.created|timesince }}</div>
            {% endif %}

            <h2 class="news__title--outstanding">
              <a href="{% url 'articulo_app:article-detail' news.category|slugify news.slug %}">
                {{ news.title }}
              </a>
            </h2>
            <p class="news__description--outstanding">{{ news.description|truncatechars_html:90 }}</p>
            <a href="{% url 'articulo_app:article-detail' news.category|slugify news.slug %}" class="news__link">Ver más...</a>
          </div>
        </article>

      {% endfor %}

    </div> <!-- fin de noticas standar -->

  </main>
  {% include "include/footer.html" %}

{% endblock %}

napendice/templates/home/search.html
{% extends "home/base_home.html" %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Noticias del Perú y el mundo |
  {{ portada.title }} |
  {% for destacado in destacados %}
    {{ destacado.title }} |
  {% endfor %}
    apendice | apendicepe
{% endblock %}

{% block description %}
  Noticias del Perú y el mundo, ultimas noticas de politica, investigacion, actualidad, gobierno, peru, en apendice.pe.
{% endblock %}

{% block content %}
  {% include "include/header.html" %}
  <main class="main">
      <div class="ed-item">
        <h3 class="title-more-news">
          Resultados de Busqueda
        </h3>
      </div>
    <div class="news-columns">
      <div class="news-column">

        {% for destacado in articles %}
          <article class="news news--outstanding">
            <div class="news__image">
              <img src="{{ destacado.image.url }}" alt="{{ destacado.title }}" />
            </div>
            <div class="news__body">
              <div class="news__date">{{ destacado.category }}</div>
              <h2 class="news__title--outstanding">
                <a href="{% url 'articulo_app:article-detail' destacado.category|slugify destacado.slug %}">
                  {{ destacado.title }}
                </a>
              </h2>
              <p class="news__description--outstanding">{{ destacado.description|truncatechars_html:90 }}</p>
              {% if destacado.date != '' %}
                <div class="news__date">Hace {{ destacado.date|timesince }}</div>
              {% else %}
                <div class="news__date">Hace {{ destacado.created|timesince }}</div>
              {% endif %}
              <a href="{% url 'articulo_app:article-detail' destacado.category|slugify destacado.slug %}" class="news__link">Ver más...</a>
            </div>
          </article>
        {% endfor %}

      </div>
    </div> <!-- fin de noticias principales -->

    <div class="ed-container">
      <div class="ed-item s-100">
        <div class="divider--top"></div>
      </div>
      <div class="ed-item">
        <h3 class="title-more-news">
          Más noticias
        </h3>
      </div>
    </div>

    <div class="ed-container">

      {% for news in standar %}

        <article class="ed-item s-100 m-1-3 l-25 news news--standar">
          <div class="news__image">
            <img src="{{ news.image.url }}" alt="{{ news.title }}" />
          </div>
          <div class="news__body">
            <div class="news__date">Hace {{ news.category }}</div>
            <h2 class="news__title--outstanding">
              <a href="{% url 'articulo_app:article-detail' news.category|slugify news.slug %}">
                {{ news.title }}
              </a>
            </h2>
            <p class="news__description--outstanding">{{ news.description|truncatechars_html:90 }}</p>
            {% if news.date != '' %}
              <div class="news__date">Hace {{ news.date|timesince }}</div>
            {% else %}
              <div class="news__date">Hace {{ news.created|timesince }}</div>
            {% endif %}
            <a href="{% url 'articulo_app:article-detail' news.category|slugify news.slug %}" class="news__link">Ver más...</a>
          </div>
        </article>

      {% endfor %}

    </div> <!-- fin de noticas standar -->

  </main>
  {% include "include/footer.html" %}

{% endblock %}