napendice/applications/articulo/urls.py
# django
from django.conf.urls import include, url

# local
from . import views

app_name="articulo_app"

urlpatterns = [

    # urls para la aplicacion articulo
    url(
        r'^ultimas-noticias-peru/$',
        views.ArticleListView.as_view(),
        name='article-list'
    ),
    url(
        r'^(?P<category>[-\w]+)/(?P<pk>\d+)/$',
        views.ArticleCategoryView.as_view(),
        name='article-category'
    ),
    url(
        r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.ArticleDetailView.as_view(),
        name='article-detail'
    ),

]

napendice/applications/home/urls.py
# django
from django.conf.urls import include, url

# local
from . import views

app_name="home_app"

urlpatterns = [
    # urls para la aplicacion home
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^buscar-noticias/$',
        views.ArticleListView.as_view(),
        name='buscar'
    ),
]

napendice/napendice/urls.py
#
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #urls para miscelanea
    url(r'^', include('applications.miscelanea.urls')),
    # urls para la aplicacion home
    url(r'^', include('applications.home.urls')),
    # urls para la aplicacion articulo
    url(r'^', include('applications.articulo.urls')),
    #
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

napendice/templates/include/footer.html
<footer class="main-footer">
  <div class="ed-container">
    <div class="ed-item m-main-start s-100 m-40">
      2016 © Apéndice, todos los derechos reservados
    </div>
    <div class="ed-item s-main-center m-main-end s-100 m-40">
      Desarrollado por <a href="http://www.neunapp.com"> neunapp</a>
    </div>
  </div>
</footer>

napendice/templates/include/header.html
{% load staticfiles %}
<div class="principal-header" style="background:#424242;">
    <ul class="principal-header__ul">
        <li class="principal-header__ul__li">
            <a href="{% url 'articulo_app:article-list' %}" class="principal-header__ul__li__a">
                Lo último
            </a>
        </li>
        {% for category in myCategorys %}
        <li class="principal-header__ul__li">
            <a href="{% url 'articulo_app:article-category' category.name|slugify category.pk %}" class="principal-header__ul__li__a">{{ category.name|title }}</a>
        </li>
        {% endfor %}
    </ul>
    <form class="principal-header__search" action="/buscar-noticias" method="get">{% csrf_token %} {{form.kword}}
        <button type="submit" class="principal-header__search__btn">
            <i class="fas fa-search"></i>
        </button>
    </form>
</div>

<div class="mov-header">
    <div class="mov-header__head">
        <i id="menu-icon" class="fas fa-bars mov-header__head__icon"></i>
        <a href="/" class="mov-header__head__link">Apendice</a>
    </div>
    <div id="mov-header__menu" class="mov-header__menu">
        <ul class="mov-header__menu__ul">
            <li class="mov-header__menu__ul__li">
                <a href="{% url 'articulo_app:article-list' %}" class="mov-header__menu__ul__li__a">
                    Lo último
                </a>
            </li>
            {% for category in myCategorys %}
            <li class="mov-header__menu__ul__li">
                <a href="{% url 'articulo_app:article-category' category.name|slugify category.pk %}" class="mov-header__menu__ul__li__a">{{ category.name|title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<!-- <header style="width: 100%;height: 200px;">
	<img src="{{home_banner.image.url}}" alt="{{home_banner.title}}" style="width: 100%;height: 100%;">
</header> -->
<header class="main-header cross-center">
    <div class="ed-container">
        <div class="ed-item s-45 m-35 main-logo">
            <a href="{% url 'home_app:index' %}">
                <img src="{% static 'img/logo-apendice.png' %}" alt="logo-apendice">
            </a>
        </div>

        <div class="ed-item s-55 m-65 cross-center main-end">
            <div class="social">
                <a href="https://www.facebook.com/apendice.pe" target="_blanck" class="social--facebook">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="https://twitter.com/apendicepe" target="_blanck" class="social--twitter">
                    <i class="fab fa-twitter"></i>
                </a>
            </div>
        </div>
    </div>
</header>

napendice/templates/include/header2.html
{% load staticfiles %}

<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="header-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<header style="width: 100%;height: 200px;">
	<img src="{{home_banner.image.url}}" alt="{{home_banner.title}}" style="width: 100%;height: 100%;">
</header>
<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
					<li> &emsp;&emsp;&emsp;&emsp;&emsp;</li>
          <li class="main-menu__item"><a href="{% url 'articulo_app:article-list' %}">Lo último</a></li>
			{% for category in myCategorys %}
					<li class="main-menu__item">
						<a href="{% url 'articulo_app:article-category' category.name|slugify category.pk %}">{{ category.name|title }}</a>
					</li>
			{% endfor %}
    </ul>
	</div>
  <div class="top-bar-right">
    <form action="/buscar-noticias" method="get">{% csrf_token %}
    <ul class="menu">
      <li>{{form.kword}}</li>
      <li><button type="submit" class="button">Buscar</button></li>
    </ul>
    </form>
  </div>
</div>
<!-- <header class="main-header cross-center">
	<div class="ed-container">
		<div class="ed-item s-45 m-90 main-logo" style="border:solid;">
			<a href="{% url 'home_app:index' %}">
				<img src="{% static 'img/logo-apendice.png' %}" alt="logo-apendice">
			</a>
		</div>

		<div class="ed-item s-55 m-10 cross-center main-end">
			<div class="social">
				<a href="https://www.facebook.com/apendice.pe" class="social--facebook"><i class="fa fa-facebook"></i></a>
				<a href="https://twitter.com/apendicepe" class="social--twitter"><i class="fa fa-twitter"></i></a>
			</div>
		</div>
	</div>
</header> --> <!-- .main-header -->
<div class="divider--bottom"></div>

napendice/templates/include/header3.html
{% load staticfiles %}

<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu">
					<li> &emsp;&emsp;&emsp;&emsp;&emsp;</li>
			{% for category in myCategorys %}
					<li class="main-menu__item">
						<a href="{% url 'articulo_app:article-category' category.name|slugify category.pk %}">{{ category.name|title }}</a>
					</li>
			{% endfor %}
    </ul>
	</div>
  <div class="top-bar-right">
    <form action="/buscar-noticias" method="get">{% csrf_token %}
    <ul class="menu">
      <li>{{form.kword}}</li>
			<li><button type="submit" class="button">Buscar</button></li>
			<h3 class="prueba">preba</h3>
    </ul>
    </form>
  </div>
</div>
<header class="main-header cross-center">
	<div class="ed-container">
		<div class="ed-item s-45 m-35 main-logo">
			<a href="{% url 'home_app:index' %}">
				<img src="{% static 'img/logo-apendice.png' %}" alt="logo-apendice">
			</a>
		</div>

		<div class="ed-item s-55 m-65 cross-center main-end">
			<!--<div class="social">
				<form method="get" class="form-horizontal">{% csrf_token %}
     		<input type="text" placeholder="Buscar ..." required>
     		<button type="submit" hidden="false">Buscar</button>
 				</form>
			</div>-->
			<div class="social">
				<a href="https://www.facebook.com/apendice.pe" class="social--facebook"><i class="fa fa-facebook"></i></a>
				<a href="https://twitter.com/apendicepe" class="social--twitter"><i class="fa fa-twitter"></i></a>
			</div>
		</div>
	</div>
</header> <!-- .main-header -->
<div class="divider--bottom"></div>

napendice/templates/include/menu.html
{% load staticfiles %}

<div class="nav">
<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Administrador Apendice</li>
      <li><a href="{% url 'articulo_app:article-list' 2 %}">Inicio</a></li>
      <li>
        <a href="#">Notas</a>
        <ul class="menu vertical">
          <li><a href="{% url 'articulo_app:article-add' %}">Nueva</a></li>
          <li><a href="{% url 'articulo_app:article-list' 0 %}">Publicadas</a></li>
          <li><a href="{% url 'articulo_app:article-list' 1 %}">Borrador</a></li>
          <li><a href="{% url 'articulo_app:article-list' 2 %}">Todas</a></li>
        </ul>
      </li>
      <li><a href="{% url 'miscelanea_app:medios-list' %}">Medios</a></li>
      <li><a href="#">Categorias</a></li>
      <li><a href="#">Tags</a></li>
      <li>
        <a href="#">Estadisticas</a>
        <ul class="menu vertical nested">
          <li><a href="#">Mas Visitados</a></li>
          <li><a href="#">Mas Comentados</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'users_app:logout' %}">Salir</a>
      </li>
    </ul>
  </div>
</div>
</div>